name: Make

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2

    - name: Run make
      run: make

    - name: Check valide name
      run: find panoramix