name: Make

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run make
      run: make
    - name: Check valide executable name
      run: find panoramix

  clean:
    needs: make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run make clean
      run: make clean

  fclean:
    needs: clean
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run make fclean
      run: make fclean

  re:
    needs: fclean
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run make re
      run: make re
